version: "3"

services:
  backend:
    build: ./backend
    container_name: chatverse-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npx nodemon server.js

  frontend:
    build: ./frontend
    container_name: chatverse-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev -- --host